name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  http: ^1.3.0
  geolocator: ^13.0.4
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.4
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.5
  google_maps_flutter: ^2.5.34
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/map_style.json
    - assets/icons/food_marker.png
    - assets/icon.png  # Ensure your app icon is placed here

# Optional: Add custom fonts if needed
# fonts:
#   - family: Poppins
#     fonts:
#       - asset: assets/fonts/Poppins-Regular.ttf
#       - asset: assets/fonts/Poppins-Bold.ttf
#         weight: 700
